/** Códigos estables para cliente y logs (no cambiar sin versión de API). */
export enum BarAccessDenialReason {
  BAR_NOT_FOUND = 'BAR_NOT_FOUND',
  SUBSCRIPTION_MISSING = 'SUBSCRIPTION_MISSING',
  SUBSCRIPTION_SUSPENDED = 'SUBSCRIPTION_SUSPENDED',
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED',
  SUBSCRIPTION_PAST_DUE = 'SUBSCRIPTION_PAST_DUE',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  TRIAL_EXPIRED = 'TRIAL_EXPIRED',
  QR_DISABLED = 'QR_DISABLED',
  PROMOTIONS_DISABLED = 'PROMOTIONS_DISABLED',
}
