ALTER TYPE "NotificationType" ADD VALUE 'SPECIAL_DRINK_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'SPECIAL_DRINK_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'SPECIAL_DRINK_FLAGGED';
ALTER TYPE "NotificationType" ADD VALUE 'SPECIAL_DRINK_PUBLISHED';
ALTER TYPE "NotificationType" ADD VALUE 'PROMOTION_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'PROMOTION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'PROMOTION_FLAGGED';
ALTER TYPE "NotificationType" ADD VALUE 'PROMOTION_PUBLISHED';
