ALTER TYPE "NotificationType" ADD VALUE 'ROOFTOP_VERIFIED';
ALTER TYPE "NotificationType" ADD VALUE 'ROOFTOP_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'ROOFTOP_PACKAGE_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'ROOFTOP_PACKAGE_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'ROOFTOP_PACKAGE_FLAGGED';
ALTER TYPE "NotificationType" ADD VALUE 'ROOFTOP_PACKAGE_PUBLISHED';
