ALTER TYPE "BarMissionTemplate" ADD VALUE 'RESERVE_PARTY_OF_TWO';
ALTER TYPE "NotificationType" ADD VALUE 'RESERVATION_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'RESERVATION_CONFIRMED';
ALTER TYPE "NotificationType" ADD VALUE 'RESERVATION_DECLINED';
ALTER TYPE "NotificationType" ADD VALUE 'RESERVATION_CANCELLED';
